package com.ksa.financing.risk.domain.model;

public enum AuditEventType {
    INTERNAL_CHECK_NID_FORMAT,
    INTERNAL_CHECK_CIF_LOOKUP,
    INTERNAL_CHECK_DUPLICATE_MOBILE,
    INTERNAL_CHECK_BLACKLIST,
    INTERNAL_CHECK_FRAUD_HISTORY,
    INTERNAL_CHECK_DEVICE_FINGERPRINT,
    INTERNAL_CHECK_VELOCITY,
    INTERNAL_CHECK_ACCOUNT_LOCK,
    INTERNAL_CHECK_INTERNAL_SANCTIONS,
    INTERNAL_CHECK_RISK_SCORE
}
