apiVersion: v1
kind: Namespace
metadata:
  name: logging
  labels:
    name: logging
    app.kubernetes.io/name: elk-stack
    app.kubernetes.io/component: logging
    app.kubernetes.io/part-of: ksa-financing-platform
