package com.ksa.financing.middleware.domain.model;

public enum ProviderCategory {
    IDENTITY, CREDIT_BUREAU, GOVERNMENT, COMMUNICATION,
    OPEN_BANKING, COMMODITY_TRADING, PROMISSORY_NOTES,
    DIGITAL_SIGNING, NOTIFICATIONS, BANKING, PAYMENT_GATEWAY,
    INCOME_VERIFICATION, FINANCIAL, AML_SCREENING
}
